name: Wheels

on:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      # Set up Python 3.10
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0

      - name: Build wheels
        env:
          CIBW_BUILD: "cp310-*"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Repair wheel
        run: |
          delocate-wheel --require-archs arm64 -w repaired_wheel wheelhouse/*.whl
        continue-on-error: true  # Allow the job to proceed even if this fails

      - name: Upload wheel artifact
        if: always()  # Ensure this step always runs
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels
          path: wheelhouse/
